import { createSlice } from "@reduxjs/toolkit";
export const dataSlice = createSlice({
    name: "data",
    initialState: {
        params: [],
        filter: [],
        product: [
            {
                id: 1001, name: "Quartz Belt Watch", price: 400.00, image: "/assets/images/product1.png", brand: "TOM FORD", categories: ["men", "women", "accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/review-1.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-2.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-3.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-3.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },

            {
                id: 1002, name: "Women Freshwash", price: 350.00, image: "/assets/images/product2.png.webp", brand: "Beauty ", categories: ["women"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office.After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook.He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company.Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting.John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half- length portrait of a dark - skinned lady with a vacant expression and large drooping breasts.It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/beautiful-woman-avatar-character-icon-free-vector.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 3 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" }
            },

            {
                id: 1003, name: "Room Flash Light", price: 200.00, image: "/assets/images/product3.png.webp", brand: "Archer", categories: ["men", "accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/flat-male-avatar-image-beard-hairstyle-businessman-profile-icon-vector-179285629.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4 },
                    { name: "Blake Ruiz", image: "/assets/images/flat-male-avatar-image-beard-hairstyle-businessman-profile-icon-vector-179285629.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 2.5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" }
            },
            {
                id: 1004, name: "Perfume", price: 150.00, image: "/assets/images/product4.png.webp", brand: "Dior", categories: ["men", "perfume"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/review-2.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 1 },
                    { name: "Blake Ruiz", image: "/assets/images/review-3.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 2.5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },
            {
                id: 1005, name: "Man Office Bag", price: 100.00, image: "/assets/images/product5.png.webp", brand: "Coach", categories: ["men", "accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/flat-male-avatar-image-beard-hairstyle-businessman-profile-icon-vector-179285629.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4 },
                    { name: "Blake Ruiz", image: "/assets/images/avatar-icon002_750950-52.avif", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 1.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-3.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },
            {
                id: 1006, name: "Charging Car", price: 240.00, image: "/assets/images/product6.png.webp", brand: "Car and Driver", categories: ["accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/flat-male-avatar-image-beard-hairstyle-businessman-profile-icon-vector-179285629.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4 },
                    { name: "Blake Ruiz", image: "/assets/images/avatar-icon002_750950-52.avif", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 1.5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },
            {
                id: 1007, name: "Blutooth Speaker", price: 450.00, image: "/assets/images/product7.png.webp", brand: "JBL", categories: ["men", "accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/flat-male-avatar-image-beard-hairstyle-businessman-profile-icon-vector-179285629.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },
            {
                id: 1008, name: "charger", price: 650.00, image: "/assets/images/product8.png.webp", brand: "Apple", categories: ["men", "accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/beautiful-woman-avatar-character-icon-free-vector.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 3 },
                    { name: "Blake Ruiz", image: "/assets/images/121859823-male-avatar-icon-or-portrait-handsome-young-man-face-with-beard-vector-illustration.jpg", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },
            {
                id: 1009, name: "Quartz Belt Watch", price: 400.00, image: "/assets/images/product1.png", brand: "TOM FORD", categories: ["men", "women", "accessories"], introduction: "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time give you the pleasant warm feeling during the winter.", description: "Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a child’s painting set for her birthday and it was with this that she produced her first significant work, a half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly named Hangover by Beryls husband and", colors: ["#ffffff", "#FFC300", "#ffb6c1", "#ff0000"], review: [
                    { name: "Blake Ruiz", image: "/assets/images/review-1.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-2.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-3.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                    { name: "Blake Ruiz", image: "/assets/images/review-3.png.webp", comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo", rate: 4.5 },
                ], specification: { width: "128mm ", height: "508mm", weight: "52gm", qualitychecking: "yes", eachboxcontains: "60pcs" },
            },
        ]
    },
    reducers: {
        addParams: (state, action) => {
            state.params = action.payload
            state.filter = state.product.slice().sort((a, b) => {
                let result = 0

                state.params.every((srch) => {
                    if (srch[0] === "sort") {
                        if (srch[1] === "Highest to Lowest") {
                            result = b.price - a.price;
                        } else if (srch[1] === "Lowest to Highest") {
                            result = a.price - b.price;
                        }
                    }
                    return true
                })

                return result
            }).filter((product) => {
                return state.params.every((srch) => {
                    if (srch[0] === "category") {
                        return product.categories.some((cat) => srch[1].includes(cat))
                    } else if (srch[0] === "brands") {
                        return srch[1].includes(product.brand)
                    }
                    else if (srch[0] == "price") {
                        const price = srch[1].split(",")
                        return product.price >= price[0] && product.price <= price[1]
                    }
                    return true
                })
            })

            console.log("Sorted and Filtered:", state.filter)


        },
    }
})

export const { addParams } = dataSlice.actions
export const products = (state) => state.data.product
export const sm = (state) => state.data.product
export const dataFilter = (state) => state.data.filter
export default dataSlice.reducer